const animals = [
  {
    name: 'Bongo',
    image: '/src/assets/animalsImages/bongo.jpg',
    type: 'Dog',
    race: 'Golden Retriever',
    gender: 'male',
    age: '2 years',
    color: 'Golden',
    location: 'Bucharest',
  },
  {
    name: 'Roblet',
    image: '/src/assets/animalsImages/roblet.jpg',
    type: 'Dog',
    race: 'Pug',
    gender: 'male',
    age: '2 years',
    color: 'Brown',
    location: 'Lucknow',
  },
  {
    name: 'Sipper',
    image: '/src/assets/animalsImages/sipper.jpg',
    type: 'Dog',
    race: 'Husky',
    gender: 'male',
    age: '6 years',
    color: 'Brown and white',
    location: 'Mogi das Cruzes',
  },
  {
    name: 'Russia',
    image: '/src/assets/animalsImages/russia.jpg',
    type: 'Cat',
    race: 'Persian',
    gender: 'Female',
    age: '2.5 years',
    color: 'White',
    location: 'Manchester',
  },
  {
    name: 'Mia',
    image: '/src/assets/animalsImages/mia.jpg',
    type: 'Rabit',
    race: 'Rabbit',
    gender: 'Female',
    age: '1 year',
    color: 'White',
    location: 'Bucharest',
  },
  {
    name: 'Zombo',
    image: '/src/assets/animalsImages/zombo.webp',
    type: 'Cat',
    race: 'Persian',
    gender: 'Female',
    age: '3 years',
    color: 'White',
    location: 'Bucharest',
  },
];

export default animals;
