export const posts = [
  {
    id: 1,
    poster: 'src/assets/blogImages/b1-poster.png',
    title: 'Adopting A Chihuahua/Beagle Mix',
    description: 'I know, I was surprised to find out that a Chihuahua/beagle mix was a thing, too, but lo and behold, the Cheagle is very much a thing....',
    read: '/blog/read',
  },
  {
    id: 2,
    poster: 'src/assets/blogImages/b2-poster.png',
    title: "Kafka's blog:",
    description: "Today, I'm writing down this blog to introduce you to Kafka, my cat. Though, we rarely use this name. It's either Bibou or Bibouch....",
    read: '/blog/read',
  },
  {
    id: 3,
    poster: 'src/assets/blogImages/b3-poster.png',
    title: "Kafka's blog:",
    description: "Today, I'm writing down this blog to introduce you to Kafka, my cat. Though, we rarely use this name. It's either Bibou or Bibouch....",
    read: '/blog/read',
  },
  {
    id: 4,
    poster: 'src/assets/blogImages/b4-poster.png',
    title: 'KEEPING DOGS HAPPY',
    description: "Dogs are great pets, wonderful companions and show you love no matter what! It isn't really hard to keep your dog happy....",
    read: '/blog/read',
  },
  {
    id: 5,
    poster: 'src/assets/blogImages/b5-poster.png',
    title: 'Pets are not Toys',
    description: 'Most people view pets as toys rather than living beings with real feelings. Firstly, instead of adopting them....',
    read: '/blog/read',
  },
  {
    id: 6,
    poster: 'src/assets/blogImages/b6-poster.png',
    title: 'All about pet ownership, love, caring, helping stray dogs',
    description: 'So lets begin with my story. I know no one is going to ask this question but still I ask you this question how do you feel being a pet owner?...',
    read: '/blog/read',
  },
  {
    id: 7,
    poster: 'src/assets/blogImages/b7-poster.png',
    title: 'Tips For New Feral Rescue Kitten Owners',
    description: 'Have you just adopted your first feral rescue kitten? Or maybe you’ve fallen in love with one but are unsure how to help them become confident, happy domestic cats....',
    read: '/blog/read',
  },
  {
    id: 8,
    poster: 'src/assets/blogImages/b8-poster.png',
    title: 'Stray Dogs are Social Responsibility',
    description: "We often thinks how we should live but didn't ever realises how stray animals live...",
    read: '/blog/read',
  },
  {
    id: 9,
    poster: 'src/assets/blogImages/b9-poster.png',
    title: 'DOGS ARE NOT PERILOUS',
    description: 'Dogs only exhibit aggressive behavior when there is a good reason for it...',
    read: '/blog/read',
  },
  {
    id: 10,
    poster: 'src/assets/blogImages/b10-poster.png',
    title: 'MY MEMORABLE ENCOUNTERS WITH ANIMALS',
    description: 'Having strict parents, I was never allowed to have pets inside the house. But I had my fair share of experience playing with strays, feeding them, and bonding with them...',
    read: '/blog/read',
  },
  {
    id: 11,
    poster: 'src/assets/blogImages/b11-poster.png',
    title: 'Who names a dog Darryl?',
    description: 'I’ve been fostering dogs with my local humane society for the last 20 years, and my first ‘foster fail’ happened 2 years ago with a dog named Darryl...',
    read: '/blog/read',
  },
  {
    id: 12,
    poster: 'src/assets/blogImages/b12-poster.png',
    title: 'Rescue Rooster',
    description: '‘Has anyone lost a chicken? We’ve one at the shop!’ This was the facebook post we saw...',
    read: '/blog/read',
  },
  {
    id: 13,
    poster: 'src/assets/blogImages/b13-poster.png',
    title: 'The best pet is a guinea pig',
    description: 'This is about my experience owning guinea pigs as pets. I grew up owning dogs that were Collies, Jack Russell Terriers, and mutts...',
    read: '/blog/read',
  },
  {
    id: 14,
    poster: 'src/assets/blogImages/b14-poster.png',
    title: 'Rantings of a pet-lover who hasn’t had a pet yet',
    description: 'This article might be pretty different from the other articles you will find here. Just like the title says, this will be me ranting about my dream of having a pet companion(s)...',
    read: '/blog/read',
  },
  {
    id: 15,
    poster: 'src/assets/blogImages/b15-poster.png',
    title: 'A Dog’s Perspective:',
    description: 'Hi, I’m Kalu, and I just survived a disaster called the festival of lights!..',
    read: '/blog/read',
  },

];
